openapi: 3.0.1
info:
  title: Order-Process
  description: ''
  version: '1.0'
servers:
  - url: https://apim-demo-bb.azure-api.net/processOrder
paths:
  /new:
    post:
      summary: New Order
      operationId: new-order
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]